apiVersion: v2
name: pet-battle-analytics
description: Pet Battle Analytics
type: application
version: 1.0.0
appVersion: 1.0.0
home: https://petbattle.github.io/helm-charts
icon: https://avatars1.githubusercontent.com/u/68044996?s=200&v=4
maintainers:
- name: noelo
