{{- if .Values.analytics.enabled }}
kind: List
metadata:
  resourceVersion: ""
  selfLink: "" 
apiVersion: v1
items:
- apiVersion: v1
  data:
    fathom-script.js: "<!-- Fathom - simple website analytics - https://github.com/usefathom/fathom
    -->\n<script>\n(function(f, a, t, h, o, m){\n\ta[h]=a[h]||function(){\n\t\t(a[h].q=a[h].q||[]).push(arguments)\n\t};\n\to=f.createElement('script'),\n\tm=f.getElementsByTagName('script')[0];\n\to.async=1;
    o.src=t; o.id='fathom-script';\n\tm.parentNode.insertBefore(o,m)\n})(document,
    window, '//{{ (lookup "route.openshift.io/v1" "Route" .Release.Namespace "fathom").spec.host }}/tracker.js', 'fathom');\nfathom('set',
    'siteId', 'bbb');\nfathom('trackPageview');\n</script>\n<!-- / Fathom -->\n"
  kind: ConfigMap
  metadata:
    name: fathom-config
    labels:
      app: fathom
      app.kubernetes.io/component: fathom
      app.kubernetes.io/instance: pet-battle-analytics  
{{- end}}