{{- if .Values.ingress.enabled -}}
{{- $fullName := include "matomo.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if eq .Values.ingress.type "default" -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "matomo.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls.default }}
  tls:
    {{- range .Values.ingress.tls.default }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ . }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
          {{- end }}
    {{- end }}
{{- else if eq .Values.ingress.type "traefik" -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "matomo.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "matomo.labels" . | nindent 4 }}
spec:
  entryPoints:
    {{- if .Values.ingress.tls.traefik }}
    - websecure
    {{- else }}
    - web
    {{- end }}
  routes:
    {{- range .Values.ingress.hosts }}
    {{- $host := .host }}
    - match: Host(`{{ $host }}`) && ({{ include "matomo.traefik.joinpaths" (dict "paths" .paths) }})
      kind: Rule
      services:
        - name: {{ $fullName }}
          port: {{ $svcPort }}
    {{- end }}
  {{- if .Values.ingress.tls.traefik }}
  tls:
    certResolver: {{ .Values.ingress.tls.traefik }}
  {{- end }}
{{- end }}
{{- end }}