apiVersion: v1
kind: Secret
metadata:
  name: {{ template "matomo.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "matomo.labels" . | nindent 4 }}
data:
  ALLOW_EMPTY_PASSWORD: {{ "no" | b64enc }}
  MATOMO_HOST: {{ .Values.matomo.host | b64enc }}
  MATOMO_USERNAME: {{ .Values.matomo.username | b64enc }}
  MATOMO_PASSWORD: {{ .Values.matomo.password | b64enc }}
  MATOMO_EMAIL: {{ .Values.matomo.email | b64enc }}
  MATOMO_WEBSITE_NAME: {{ .Values.matomo.website_name | b64enc }}
  MATOMO_WEBSITE_HOST: {{ .Values.matomo.website_host | b64enc }}
  {{ $mariadb_data := dict "Values" .Values.mariadb "Chart" (dict "Name" "mariadb") "Release" .Release }}
  {{ $database_host := include "mariadb.primary.fullname" $mariadb_data }}
  MATOMO_DATABASE_HOST: {{ $database_host | b64enc }}
  MATOMO_DATABASE_PORT_NUMBER: {{ .Values.mariadb.primary.service.port | toString | b64enc }}
  MATOMO_DATABASE_NAME: {{ .Values.mariadb.auth.database | b64enc }}
  MATOMO_DATABASE_USER: {{ .Values.mariadb.auth.username | b64enc }}
  MATOMO_DATABASE_PASSWORD: {{ .Values.mariadb.auth.password | b64enc }}
  {{- $redis_data := dict "Values" .Values.redis "Chart" (dict "Name" "redis") "Release" .Release }}
  {{- $cache_host := include "redis.fullname" $redis_data }}
  MATOMO_CACHE_HOST: {{ printf "%s-master" $cache_host | b64enc }}
  MATOMO_CACHE_PORT_NUMBER: {{ .Values.redis.redisPort | toString | b64enc }}
  MATOMO_CACHE_PASSWORD: {{ .Values.redis.password | toString | b64enc }}
  MATOMO_CACHE_DATABASE_NUMBER: {{ "0" | b64enc }}